name = "linnil1-profile"
workers_dev = false
compatibility_date = "2023-06-28"
route = { pattern = "linnil1.tw/*", zone_name = "linnil1.tw" }

main = ".output/server/index.mjs"
account_id = "84360be8d748ddadfd6897136883929a"

[[kv_namespaces]]
binding = "linnil1_profile"
id = "846eab0b92324f499ebccd26264dc69b"

[site]
bucket = ".output/public"
